/**
 * @file commands/init.ts
 * @description `sanix init "<description>"` — natural-language project scaffolder.
 *
 *   sanix init "REST API with Express, PostgreSQL, JWT auth"
 *     --name <project-name>      Project name (default: auto from description)
 *     --template <template>      Use a specific built-in template
 *     --dir <path>               Output directory (default: ./<name>)
 *     --no-tests                 Skip test setup
 *     --no-docker                Skip Dockerfile
 *     --no-ci                    Skip CI/CD setup
 *     --git                      Initialize a git repo
 *     --json                     JSON output of created files
 *
 * The command detects the user's intent from the description (language,
 * framework, database, auth, features), then generates a complete
 * project skeleton. If an LLM provider is configured + reachable, the
 * file contents are generated by the LLM; otherwise the built-in
 * templates are used.
 *
 * Built-in templates:
 *   - `express-api`  — Express + TypeScript + PostgreSQL + JWT + tests
 *   - `next-app`     — Next.js + Tailwind + Prisma + Auth.js
 *   - `react-app`    — Vite + React + TypeScript + Tailwind
 *   - `python-api`   — FastAPI + SQLAlchemy + JWT + pytest
 *   - `cli-tool`     — Commander.js + TypeScript + tests
 *   - `library`      — TypeScript library with tsup + vitest
 *
 * @packageDocumentation
 */

import type { Command } from 'commander';
import chalk from 'chalk';
import { join, resolve, basename } from 'node:path';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import type { SanixContext } from '../bootstrap.js';

/** Parsed options for `sanix init`. */
export interface InitCommandOptions {
  name?: string;
  template?: string;
  dir?: string;
  tests?: boolean;
  docker?: boolean;
  ci?: boolean;
  git?: boolean;
  json?: boolean;
}

/** A single file in a scaffolded project. */
export interface ScaffoldFile {
  /** Relative path from the project root (e.g. `src/index.ts`). */
  path: string;
  /** File content. */
  content: string;
  /** Whether to overwrite an existing file (default: false). */
  overwrite?: boolean;
}

/** Description of a built-in template. */
export interface TemplateDef {
  /** Template id (matches `--template`). */
  id: string;
  /** Human-readable name. */
  name: string;
  /** One-line description. */
  description: string;
  /** Returns true if the description matches this template. */
  matches: (desc: string) => boolean;
  /** Build the files for the template. */
  build: (ctx: TemplateBuildCtx) => ScaffoldFile[];
}

/** Context passed to a template's `build` function. */
export interface TemplateBuildCtx {
  /** Project name. */
  name: string;
  /** Original description. */
  description: string;
  /** Whether tests are included. */
  tests: boolean;
  /** Whether Docker is included. */
  docker: boolean;
  /** Whether CI is included. */
  ci: boolean;
}

/** Built-in templates. */
const TEMPLATES: TemplateDef[] = [
  {
    id: 'express-api',
    name: 'Express API',
    description: 'Express + TypeScript + PostgreSQL + JWT + tests',
    matches: (d) => /express|rest\s*api|api\s*server|backend/i.test(d),
    build: (c) => buildExpressApi(c),
  },
  {
    id: 'next-app',
    name: 'Next.js App',
    description: 'Next.js + Tailwind + Prisma + Auth.js',
    matches: (d) => /next(\.js|js)?|nextjs/i.test(d),
    build: (c) => buildNextApp(c),
  },
  {
    id: 'react-app',
    name: 'React App (Vite)',
    description: 'Vite + React + TypeScript + Tailwind',
    matches: (d) => /\breact\b|vite|spa/i.test(d),
    build: (c) => buildReactApp(c),
  },
  {
    id: 'python-api',
    name: 'Python API (FastAPI)',
    description: 'FastAPI + SQLAlchemy + JWT + pytest',
    matches: (d) => /\bpython\b|fastapi|flask|django/i.test(d),
    build: (c) => buildPythonApi(c),
  },
  {
    id: 'cli-tool',
    name: 'CLI Tool',
    description: 'Commander.js + TypeScript + tests',
    matches: (d) => /\bcli\b|command(\s*line)?\s*tool/i.test(d),
    build: (c) => buildCliTool(c),
  },
  {
    id: 'library',
    name: 'TypeScript Library',
    description: 'tsup + vitest + TypeScript',
    matches: (d) => /\blibrary\b|lib\b|npm\s*package/i.test(d),
    build: (c) => buildLibrary(c),
  },
];

/** Default template when nothing matches. */
const DEFAULT_TEMPLATE_ID = 'library';

/**
 * Register the `sanix init` command.
 *
 * @param program     - The Commander root program.
 * @param ctxProvider - Lazy context provider (called on first action).
 */
export function registerInitCommand(
  program: Command,
  ctxProvider: () => Promise<SanixContext>,
): void {
  program
    .command('init <description>')
    .description('Scaffold a new project from a natural-language description.')
    .option('--name <name>', 'Project name (default: auto from description)')
    .option('--template <template>', 'Use a specific built-in template')
    .option('--dir <path>', 'Output directory (default: ./<name>)')
    .option('--no-tests', 'Skip test setup')
    .option('--no-docker', 'Skip Dockerfile')
    .option('--no-ci', 'Skip CI/CD setup')
    .option('--git', 'Initialize a git repo after scaffolding')
    .option('--json', 'Output JSON of created files')
    .action(async (description: string, opts: InitCommandOptions) => {
      try {
        const ctx = await ctxProvider();
        await initCommand(ctx, description, opts);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        // eslint-disable-next-line no-console
        console.error(chalk.red(`\n✗ sanix init failed: ${msg}\n`));
        process.exitCode = 1;
      }
    });
}

/**
 * Run the `sanix init` command. Exposed for programmatic use.
 *
 * @param ctx         - The wired SANIX context.
 * @param description - The natural-language project description.
 * @param opts        - Parsed CLI options.
 */
export async function initCommand(
  ctx: SanixContext,
  description: string,
  opts: InitCommandOptions,
): Promise<void> {
  // 1. Detect the template (explicit > auto-detect > default).
  const template = pickTemplate(description, opts.template);
  // 2. Derive the project name.
  const name = opts.name ?? deriveName(description, template.id);
  const outDir = resolve(opts.dir ?? `./${name}`);
  // 3. Build the files.
  const buildCtx: TemplateBuildCtx = {
    name,
    description,
    tests: opts.tests !== false,
    docker: opts.docker !== false,
    ci: opts.ci !== false,
  };
  let files: ScaffoldFile[];
  let llmUsed = false;
  try {
    const llmFiles = await tryLlmScaffold(ctx, description, template, buildCtx);
    if (llmFiles) {
      files = llmFiles;
      llmUsed = true;
    } else {
      files = template.build(buildCtx);
    }
  } catch {
    files = template.build(buildCtx);
  }

  // 4. Write the files.
  if (existsSync(outDir) && existsSync(join(outDir, 'package.json')) && template.id !== 'library') {
    // For app templates, refuse to overwrite an existing project.
    throw new Error(`Output directory ${outDir} already contains a package.json. Aborting.`);
  }
  mkdirSync(outDir, { recursive: true });
  const written: Array<{ path: string; bytes: number }> = [];
  for (const f of files) {
    const fp = join(outDir, f.path);
    const dir = join(fp, '..');
    mkdirSync(dir, { recursive: true });
    if (existsSync(fp) && !f.overwrite) {
      // Skip existing files unless overwrite is set.
      continue;
    }
    writeFileSync(fp, f.content, 'utf-8');
    written.push({ path: f.path, bytes: Buffer.byteLength(f.content, 'utf-8') });
  }

  // 5. Optionally init git.
  if (opts.git) {
    const r = spawnSync('git', ['init'], { cwd: outDir, stdio: 'ignore' });
    if (r.status === 0) {
      // Initial commit.
      spawnSync('git', ['add', '-A'], { cwd: outDir, stdio: 'ignore' });
      spawnSync('git', ['commit', '-m', `chore: initial commit (scaffolded by sanix init)`], {
        cwd: outDir,
        stdio: 'ignore',
      });
    }
  }

  // 6. Report.
  if (opts.json) {
    // eslint-disable-next-line no-console
    console.log(JSON.stringify({
      template: template.id,
      name,
      dir: outDir,
      llmUsed,
      files: written,
    }, null, 2));
    return;
  }
  // eslint-disable-next-line no-console
  console.log(chalk.hex('#00D4FF')(`\n✓ Scaffolded ${chalk.cyan(name)} (${template.id}) → ${chalk.dim(outDir)}`));
  // eslint-disable-next-line no-console
  console.log(chalk.dim(`  ${llmUsed ? 'LLM-generated' : 'template-based'} • ${written.length} files\n`));
  for (const w of written) {
    // eslint-disable-next-line no-console
    console.log(`  ${chalk.green('create')} ${w.path} ${chalk.dim(`(${w.bytes} B`)}`);
  }
  // eslint-disable-next-line no-console
  console.log(chalk.hex('#FFB347')('\nNext steps:'));
  // eslint-disable-next-line no-console
  console.log(chalk.dim(`  cd ${basename(outDir)}`));
  if (template.id === 'python-api') {
    // eslint-disable-next-line no-console
    console.log(chalk.dim('  python -m venv .venv && source .venv/bin/activate'));
    // eslint-disable-next-line no-console
    console.log(chalk.dim('  pip install -r requirements.txt'));
  } else {
    // eslint-disable-next-line no-console
    console.log(chalk.dim('  npm install   # or: bun install / pnpm install'));
  }
  // eslint-disable-next-line no-console
  console.log('');
}

/** Pick a template by id, or auto-detect from the description. */
function pickTemplate(description: string, explicit?: string): TemplateDef {
  if (explicit) {
    const t = TEMPLATES.find((x) => x.id === explicit);
    if (!t) {
      throw new Error(
        `Unknown template "${explicit}". Available: ${TEMPLATES.map((x) => x.id).join(', ')}`,
      );
    }
    return t;
  }
  const lower = description.toLowerCase();
  for (const t of TEMPLATES) {
    if (t.matches(lower)) return t;
  }
  const def = TEMPLATES.find((x) => x.id === DEFAULT_TEMPLATE_ID)!;
  return def;
}

/** Derive a project name from the description or template. */
function deriveName(description: string, templateId: string): string {
  // Try to find a "called X" or "named X" in the description.
  const m = description.match(/(?:called|named)\s+["']?([a-zA-Z0-9_-]+)/i);
  if (m && m[1]) return m[1].toLowerCase();
  // Fallback: template-based default.
  const defaults: Record<string, string> = {
    'express-api': 'my-api',
    'next-app': 'my-app',
    'react-app': 'my-react-app',
    'python-api': 'my-api',
    'cli-tool': 'my-cli',
    library: 'my-lib',
  };
  return defaults[templateId] ?? 'my-project';
}

/**
 * Try to use the LLM to generate a richer scaffold. Returns `null` if no
 * LLM is available or the call fails. We give the LLM the description +
 * template id + project name, and ask it to return a JSON object mapping
 * file paths to contents. If the LLM fails or returns invalid JSON, we
 * fall back to the built-in template.
 */
async function tryLlmScaffold(
  ctx: SanixContext,
  description: string,
  template: TemplateDef,
  buildCtx: TemplateBuildCtx,
): Promise<ScaffoldFile[] | null> {
  // First, build the template files so we always have a baseline.
  const baseline = template.build(buildCtx);
  // Only attempt LLM enhancement when the router has at least one provider.
  let providers: { id: string }[] = [];
  try {
    providers = ctx.router.list().map((p) => ({ id: p.id }));
  } catch {
    providers = [];
  }
  if (providers.length === 0) return null;

  const systemPrompt = `You are a senior software architect. Generate project scaffold files based on the user's description. Return ONLY a JSON object mapping file paths to file contents. No prose, no markdown fences. Keys are relative paths (POSIX), values are the full file contents as strings. Keep each file focused and minimal but realistic.`;
  const userPrompt = `Project name: ${buildCtx.name}
Description: ${description}
Base template: ${template.id}
Include tests: ${buildCtx.tests}
Include Docker: ${buildCtx.docker}
Include CI: ${buildCtx.ci}

Generate a complete project. Return a JSON object: { "path/to/file.ext": "file content" }.`;

  try {
    const res = await ctx.router.route({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      taskType: 'code',
      maxTokens: 8000,
    });
    const text = res.content?.trim() ?? '';
    if (!text) return null;
    // Try to parse the JSON. The model may have wrapped it in fences despite
    // the instruction — strip them defensively.
    const cleaned = text
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/i, '')
      .trim();
    const parsed = JSON.parse(cleaned) as unknown;
    if (typeof parsed !== 'object' || parsed === null) return null;
    const files: ScaffoldFile[] = [];
    for (const [path, content] of Object.entries(parsed as Record<string, unknown>)) {
      if (typeof content !== 'string') continue;
      files.push({ path, content });
    }
    if (files.length === 0) return null;
    // Merge: prefer LLM-generated paths, but always include a README if missing.
    const have = new Set(files.map((f) => f.path));
    for (const b of baseline) {
      if (!have.has(b.path)) files.push(b);
    }
    return files;
  } catch {
    return null;
  }
}

// ─── Template builders ─────────────────────────────────────────────────

/** Build the `express-api` template. */
function buildExpressApi(c: TemplateBuildCtx): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: c.name,
      version: '0.1.0',
      type: 'module',
      scripts: {
        dev: 'tsx watch src/index.ts',
        build: 'tsc',
        start: 'node dist/index.js',
        test: c.tests ? 'vitest run' : undefined,
        lint: 'eslint src/',
      },
      dependencies: {
        express: '^4.19.0',
        pg: '^8.12.0',
        jsonwebtoken: '^9.0.0',
        bcryptjs: '^2.4.0',
        zod: '^3.24.0',
        cors: '^2.8.5',
        dotenv: '^16.4.0',
      },
      devDependencies: {
        typescript: '^5.6.0',
        '@types/express': '^4.17.0',
        '@types/node': '^22.0.0',
        '@types/pg': '^8.11.0',
        '@types/jsonwebtoken': '^9.0.0',
        '@types/bcryptjs': '^2.4.0',
        '@types/cors': '^2.8.0',
        tsx: '^4.19.0',
        ...(c.tests ? { vitest: '^2.1.0', supertest: '^7.0.0', '@types/supertest': '^6.0.0' } : {}),
      },
    }, null, 2),
  });
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        resolveJsonModule: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist', 'test'],
    }, null, 2),
  });
  files.push({
    path: '.env.example',
    content: [
      '# Database',
      'DATABASE_URL=postgres://user:pass@localhost:5432/mydb',
      '',
      '# Auth',
      'JWT_SECRET=change-me-in-production',
      'JWT_EXPIRES_IN=24h',
      '',
      '# Server',
      'PORT=3000',
      'NODE_ENV=development',
      '',
    ].join('\n'),
  });
  files.push({
    path: '.gitignore',
    content: ['node_modules/', 'dist/', '.env', '*.log', '.DS_Store', 'coverage/'].join('\n') + '\n',
  });
  files.push({
    path: 'src/index.ts',
    content: [
      "import express from 'express';",
      "import cors from 'cors';",
      "import 'dotenv/config';",
      "import { userRoutes } from './routes/users.js';",
      "import { authRoutes } from './routes/auth.js';",
      '',
      'const app = express();',
      'const PORT = process.env.PORT ?? 3000;',
      '',
      'app.use(cors());',
      'app.use(express.json());',
      '',
      "app.get('/health', (_req, res) => res.json({ status: 'ok' }));",
      "app.use('/auth', authRoutes);",
      "app.use('/users', userRoutes);",
      '',
      'app.listen(PORT, () => {',
      '  console.log(`Server listening on http://localhost:${PORT}`);',
      '});',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/db.ts',
    content: [
      "import { Pool } from 'pg';",
      '',
      'export const pool = new Pool({',
      '  connectionString: process.env.DATABASE_URL,',
      '});',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/routes/auth.ts',
    content: [
      "import { Router } from 'express';",
      "import jwt from 'jsonwebtoken';",
      "import bcrypt from 'bcryptjs';",
      "import { pool } from '../db.js';",
      '',
      'export const authRoutes = Router();',
      '',
      'authRoutes.post("/register", async (req, res) => {',
      '  const { email, password } = req.body as { email: string; password: string };',
      '  if (!email || !password) return res.status(400).json({ error: "email + password required" });',
      '  const hash = await bcrypt.hash(password, 10);',
      '  const result = await pool.query(',
      '    "INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id, email",',
      '    [email, hash],',
      '  );',
      '  res.status(201).json(result.rows[0]);',
      '});',
      '',
      'authRoutes.post("/login", async (req, res) => {',
      '  const { email, password } = req.body as { email: string; password: string };',
      '  const result = await pool.query("SELECT * FROM users WHERE email = $1", [email]);',
      '  const user = result.rows[0];',
      '  if (!user) return res.status(401).json({ error: "invalid credentials" });',
      '  const ok = await bcrypt.compare(password, user.password_hash);',
      '  if (!ok) return res.status(401).json({ error: "invalid credentials" });',
      '  const token = jwt.sign({ sub: user.id }, process.env.JWT_SECRET!, {',
      '    expiresIn: process.env.JWT_EXPIRES_IN ?? "24h",',
      '  });',
      '  res.json({ token });',
      '});',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/routes/users.ts',
    content: [
      "import { Router } from 'express';",
      "import jwt from 'jsonwebtoken';",
      "import { pool } from '../db.js';",
      '',
      'export const userRoutes = Router();',
      '',
      'userRoutes.use((req, res, next) => {',
      '  const header = req.headers.authorization;',
      '  if (!header?.startsWith("Bearer ")) return res.status(401).json({ error: "no token" });',
      '  try {',
      '    const payload = jwt.verify(header.slice(7), process.env.JWT_SECRET!);',
      '    (req as unknown as { user: unknown }).user = payload;',
      '    next();',
      '  } catch {',
      '    res.status(401).json({ error: "invalid token" });',
      '  }',
      '});',
      '',
      'userRoutes.get("/me", async (req, res) => {',
      '  const payload = (req as unknown as { user: { sub: string } }).user;',
      '  const result = await pool.query("SELECT id, email FROM users WHERE id = $1", [payload.sub]);',
      '  res.json(result.rows[0]);',
      '});',
      '',
    ].join('\n'),
  });
  if (c.tests) {
    files.push({
      path: 'test/health.test.ts',
      content: [
        "import { describe, it, expect } from 'vitest';",
        '',
        'describe("placeholder", () => {',
        '  it("passes", () => {',
        '    expect(1 + 1).toBe(2);',
        '  });',
        '});',
        '',
      ].join('\n'),
    });
  }
  if (c.docker) {
    files.push({
      path: 'Dockerfile',
      content: [
        'FROM node:20-alpine AS builder',
        'WORKDIR /app',
        'COPY package*.json ./',
        'RUN npm ci',
        'COPY . .',
        'RUN npm run build',
        '',
        'FROM node:20-alpine',
        'WORKDIR /app',
        "ENV NODE_ENV=production",
        'COPY --from=builder /app/dist ./dist',
        'COPY --from=builder /app/node_modules ./node_modules',
        'COPY package*.json ./',
        'EXPOSE 3000',
        'CMD ["node", "dist/index.js"]',
        '',
      ].join('\n'),
    });
    files.push({
      path: 'docker-compose.yml',
      content: [
        'services:',
        '  api:',
        '    build: .',
        '    ports: ["3000:3000"]',
        '    env_file: .env',
        '    depends_on: [db]',
        '  db:',
        '    image: postgres:16-alpine',
        '    environment:',
        '      POSTGRES_USER: user',
        '      POSTGRES_PASSWORD: pass',
        '      POSTGRES_DB: mydb',
        '    ports: ["5432:5432"]',
        '    volumes: ["pgdata:/var/lib/postgresql/data"]',
        'volumes:',
        '  pgdata:',
        '',
      ].join('\n'),
    });
  }
  if (c.ci) {
    files.push({
      path: '.github/workflows/ci.yml',
      content: [
        'name: CI',
        'on: [push, pull_request]',
        'jobs:',
        '  test:',
        '    runs-on: ubuntu-latest',
        '    services:',
        '      postgres:',
        '        image: postgres:16',
        '        env: { POSTGRES_PASSWORD: pass, POSTGRES_DB: mydb }',
        '        ports: ["5432:5432"]',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/setup-node@v4',
        '        with: { node-version: "20" }',
        '      - run: npm ci',
        '      - run: npm run build',
        '      - run: npm test',
        '',
      ].join('\n'),
    });
  }
  files.push({
    path: 'README.md',
    content: [
      `# ${c.name}`,
      '',
      c.description,
      '',
      '## Getting started',
      '',
      '```bash',
      'npm install',
      'cp .env.example .env  # then edit values',
      'npm run dev',
      '```',
      '',
      '## Endpoints',
      '',
      '- `GET /health` — health check',
      '- `POST /auth/register` — register a new user',
      '- `POST /auth/login` — login, returns a JWT',
      '- `GET /users/me` — current user (requires `Authorization: Bearer <token>`)',
      '',
    ].join('\n'),
  });
  return files;
}

/** Build the `next-app` template. */
function buildNextApp(c: TemplateBuildCtx): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: c.name,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
        test: c.tests ? 'vitest' : undefined,
        db: 'prisma',
      },
      dependencies: {
        next: '^15.0.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
        '@prisma/client': '^5.20.0',
        'next-auth': '^4.24.0',
      },
      devDependencies: {
        typescript: '^5.6.0',
        '@types/node': '^22.0.0',
        '@types/react': '^19.0.0',
        '@types/react-dom': '^19.0.0',
        tailwindcss: '^4.0.0',
        prisma: '^5.20.0',
        ...(c.tests ? { vitest: '^2.1.0', '@testing-library/react': '^16.0.0' } : {}),
      },
    }, null, 2),
  });
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    }, null, 2),
  });
  files.push({
    path: '.env.example',
    content: [
      'DATABASE_URL="postgresql://user:pass@localhost:5432/mydb"',
      'NEXTAUTH_SECRET="change-me"',
      'NEXTAUTH_URL="http://localhost:3000"',
      '',
    ].join('\n'),
  });
  files.push({
    path: '.gitignore',
    content: ['node_modules/', '.next/', '.env', '*.log', '.DS_Store'].join('\n') + '\n',
  });
  files.push({
    path: 'src/app/page.tsx',
    content: [
      "export default function Home() {",
      "  return (",
      "    <main className=\"flex min-h-screen items-center justify-center\">",
      "      <h1 className=\"text-3xl font-bold\">Welcome to " + c.name + "</h1>",
      "    </main>",
      "  );",
      "}",
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/app/layout.tsx',
    content: [
      "import './globals.css';",
      '',
      "export const metadata = { title: '" + c.name + "', description: c.description };",
      '',
      "export default function RootLayout({ children }: { children: React.ReactNode }) {",
      "  return (",
      "    <html lang=\"en\">",
      "      <body>{children}</body>",
      "    </html>",
      "  );",
      "}",
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/app/globals.css',
    content: '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n',
  });
  files.push({
    path: 'prisma/schema.prisma',
    content: [
      'generator client {',
      '  provider = "prisma-client-js"',
      '}',
      '',
      'datasource db {',
      '  provider = "postgresql"',
      '  url      = env("DATABASE_URL")',
      '}',
      '',
      'model User {',
      '  id        String   @id @default(cuid())',
      '  email     String   @unique',
      '  name      String?',
      '  createdAt DateTime @default(now())',
      '}',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/lib/auth.ts',
    content: [
      "import NextAuth from 'next-auth';",
      "import CredentialsProvider from 'next-auth/providers/credentials';",
      '',
      'export const { handlers, auth, signIn, signOut } = NextAuth({',
      '  providers: [',
      '    CredentialsProvider({',
      '      name: "credentials",',
      '      credentials: {',
      '        email: { label: "Email", type: "email" },',
      '        password: { label: "Password", type: "password" },',
      '      },',
      '      async authorize() { return null; },',
      '    }),',
      '  ],',
      '});',
      '',
    ].join('\n'),
  });
  if (c.tests) {
    files.push({
      path: 'test/home.test.tsx',
      content: [
        "import { describe, it, expect } from 'vitest';",
        '',
        'describe("home", () => {',
        '  it("renders", () => {',
        '    expect(true).toBe(true);',
        '  });',
        '});',
        '',
      ].join('\n'),
    });
  }
  if (c.docker) {
    files.push({
      path: 'Dockerfile',
      content: [
        'FROM node:20-alpine AS builder',
        'WORKDIR /app',
        'COPY package*.json ./',
        'RUN npm ci',
        'COPY . .',
        'RUN npm run build',
        '',
        'FROM node:20-alpine',
        'WORKDIR /app',
        "ENV NODE_ENV=production",
        'COPY --from=builder /app/.next ./.next',
        'COPY --from=builder /app/public ./public',
        'COPY --from=builder /app/node_modules ./node_modules',
        'COPY package*.json ./',
        'EXPOSE 3000',
        'CMD ["npm", "start"]',
        '',
      ].join('\n'),
    });
  }
  if (c.ci) {
    files.push({
      path: '.github/workflows/ci.yml',
      content: [
        'name: CI',
        'on: [push, pull_request]',
        'jobs:',
        '  test:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/setup-node@v4',
        '        with: { node-version: "20" }',
        '      - run: npm ci',
        '      - run: npm run build',
        '',
      ].join('\n'),
    });
  }
  files.push({
    path: 'README.md',
    content: `# ${c.name}\n\n${c.description}\n\n## Getting started\n\n\`\`\`bash\nnpm install\ncp .env.example .env\nnpx prisma db push\nnpm run dev\n\`\`\`\n`,
  });
  return files;
}

/** Build the `react-app` (Vite) template. */
function buildReactApp(c: TemplateBuildCtx): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: c.name,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
        test: c.tests ? 'vitest' : undefined,
      },
      dependencies: {
        react: '^19.0.0',
        'react-dom': '^19.0.0',
      },
      devDependencies: {
        '@vitejs/plugin-react': '^4.3.0',
        typescript: '^5.6.0',
        '@types/react': '^19.0.0',
        '@types/react-dom': '^19.0.0',
        vite: '^6.0.0',
        tailwindcss: '^4.0.0',
        ...(c.tests ? { vitest: '^2.1.0', '@testing-library/react': '^16.0.0', jsdom: '^25.0.0' } : {}),
      },
    }, null, 2),
  });
  files.push({
    path: 'vite.config.ts',
    content: [
      "import { defineConfig } from 'vite';",
      "import react from '@vitejs/plugin-react';",
      '',
      'export default defineConfig({',
      '  plugins: [react()],',
      "  test: { environment: 'jsdom' } as never,",
      '});',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        useDefineForClassFields: true,
        lib: ['ES2022', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: 'react-jsx',
        strict: true,
      },
      include: ['src'],
    }, null, 2),
  });
  files.push({
    path: '.gitignore',
    content: ['node_modules/', 'dist/', '*.log', '.DS_Store'].join('\n') + '\n',
  });
  files.push({
    path: 'index.html',
    content: [
      '<!doctype html>',
      '<html lang="en">',
      '  <head>',
      '    <meta charset="UTF-8" />',
      '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
      `    <title>${c.name}</title>`,
      '  </head>',
      '  <body>',
      '    <div id="root"></div>',
      '    <script type="module" src="/src/main.tsx"></script>',
      '  </body>',
      '</html>',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/main.tsx',
    content: [
      "import React from 'react';",
      "import ReactDOM from 'react-dom/client';",
      "import App from './App';",
      "import './index.css';",
      '',
      "ReactDOM.createRoot(document.getElementById('root')!).render(",
      '  <React.StrictMode>',
      '    <App />',
      '  </React.StrictMode>,',
      ');',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/App.tsx',
    content: [
      "export default function App() {",
      "  return (",
      "    <div className=\"min-h-screen flex items-center justify-center\">",
      "      <h1 className=\"text-4xl font-bold\">Hello from " + c.name + "</h1>",
      "    </div>",
      "  );",
      "}",
      '',
    ].join('\n'),
  });
  files.push({
    path: 'src/index.css',
    content: '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n',
  });
  if (c.tests) {
    files.push({
      path: 'test/app.test.tsx',
      content: [
        "import { describe, it, expect } from 'vitest';",
        '',
        'describe("App", () => {',
        '  it("passes", () => { expect(true).toBe(true); });',
        '});',
        '',
      ].join('\n'),
    });
  }
  if (c.docker) {
    files.push({
      path: 'Dockerfile',
      content: [
        'FROM node:20-alpine AS builder',
        'WORKDIR /app',
        'COPY package*.json ./',
        'RUN npm ci',
        'COPY . .',
        'RUN npm run build',
        '',
        'FROM nginx:alpine',
        'COPY --from=builder /app/dist /usr/share/nginx/html',
        'EXPOSE 80',
        '',
      ].join('\n'),
    });
  }
  if (c.ci) {
    files.push({
      path: '.github/workflows/ci.yml',
      content: [
        'name: CI',
        'on: [push, pull_request]',
        'jobs:',
        '  test:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/setup-node@v4',
        '        with: { node-version: "20" }',
        '      - run: npm ci',
        '      - run: npm run build',
        '',
      ].join('\n'),
    });
  }
  files.push({
    path: 'README.md',
    content: `# ${c.name}\n\n${c.description}\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`,
  });
  return files;
}

/** Build the `python-api` (FastAPI) template. */
function buildPythonApi(c: TemplateBuildCtx): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];
  files.push({
    path: 'requirements.txt',
    content: [
      'fastapi>=0.115.0',
      'uvicorn[standard]>=0.32.0',
      'sqlalchemy>=2.0.0',
      'psycopg2-binary>=2.9.0',
      'pydantic>=2.0.0',
      'python-jose[cryptography]>=3.3.0',
      'passlib[bcrypt]>=1.7.0',
      'python-multipart>=0.0.12',
      c.tests ? 'pytest>=8.0.0' : '',
      c.tests ? 'httpx>=0.27.0' : '',
    ].filter(Boolean).join('\n') + '\n',
  });
  files.push({
    path: '.env.example',
    content: [
      'DATABASE_URL=postgresql://user:pass@localhost:5432/mydb',
      'JWT_SECRET=change-me',
      'JWT_EXPIRES_MINUTES=1440',
      '',
    ].join('\n'),
  });
  files.push({
    path: '.gitignore',
    content: ['__pycache__/', '*.pyc', '.venv/', '.env', '*.log', '.pytest_cache/'].join('\n') + '\n',
  });
  files.push({
    path: 'app/__init__.py',
    content: '',
  });
  files.push({
    path: 'app/main.py',
    content: [
      'from fastapi import FastAPI',
      'from .routers import auth, users',
      '',
      'app = FastAPI(title="' + c.name + '")',
      '',
      '',
      '@app.get("/health")',
      'def health():',
      '    return {"status": "ok"}',
      '',
      'app.include_router(auth.router)',
      'app.include_router(users.router)',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'app/db.py',
    content: [
      'import os',
      'from sqlalchemy import create_engine',
      'from sqlalchemy.orm import declarative_base, sessionmaker',
      '',
      'DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///./test.db")',
      'engine = create_engine(DATABASE_URL)',
      'SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)',
      'Base = declarative_base()',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'app/models.py',
    content: [
      'from sqlalchemy import Column, Integer, String',
      'from .db import Base',
      '',
      'class User(Base):',
      '    __tablename__ = "users"',
      '    id = Column(Integer, primary_key=True)',
      '    email = Column(String, unique=True, nullable=False)',
      '    password_hash = Column(String, nullable=False)',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'app/routers/__init__.py',
    content: '',
  });
  files.push({
    path: 'app/routers/auth.py',
    content: [
      'from fastapi import APIRouter, HTTPException',
      'from pydantic import BaseModel',
      'from passlib.context import CryptContext',
      'from jose import jwt',
      'import os, datetime',
      'from ..db import SessionLocal',
      'from ..models import User',
      '',
      'router = APIRouter(prefix="/auth")',
      'pwd = CryptContext(schemes=["bcrypt"])',
      '',
      'class Credentials(BaseModel):',
      '    email: str',
      '    password: str',
      '',
      '@router.post("/register", status_code=201)',
      'def register(creds: Credentials):',
      '    db = SessionLocal()',
      '    if db.query(User).filter_by(email=creds.email).first():',
      '        raise HTTPException(400, "email already registered")',
      '    user = User(email=creds.email, password_hash=pwd.hash(creds.password))',
      '    db.add(user); db.commit(); db.refresh(user)',
      '    return {"id": user.id, "email": user.email}',
      '',
      '@router.post("/login")',
      'def login(creds: Credentials):',
      '    db = SessionLocal()',
      '    user = db.query(User).filter_by(email=creds.email).first()',
      '    if not user or not pwd.verify(creds.password, user.password_hash):',
      '        raise HTTPException(401, "invalid credentials")',
      '    exp = datetime.datetime.utcnow() + datetime.timedelta(',
      '        minutes=int(os.environ.get("JWT_EXPIRES_MINUTES", "1440")))[',
      '    token = jwt.encode({"sub": str(user.id), "exp": exp},',
      '                       os.environ["JWT_SECRET"], algorithm="HS256")',
      '    return {"token": token}',
      '',
    ].join('\n'),
  });
  files.push({
    path: 'app/routers/users.py',
    content: [
      'from fastapi import APIRouter, Depends, HTTPException, Header',
      'from jose import jwt, JWTError',
      'import os',
      '',
      'router = APIRouter(prefix="/users")',
      '',
      'def current_user(authorization: str = Header(...)):',
      '    if not authorization.startswith("Bearer "):',
      '        raise HTTPException(401, "no token")',
      '    try:',
      '        return jwt.decode(authorization[7:], os.environ["JWT_SECRET"], algorithms=["HS256"])',
      '    except JWTError:',
      '        raise HTTPException(401, "invalid token")',
      '',
      '@router.get("/me")',
      'def me(payload: dict = Depends(current_user)):',
      '    return payload',
      '',
    ].join('\n'),
  });
  if (c.tests) {
    files.push({
      path: 'tests/test_health.py',
      content: [
        'from fastapi.testclient import TestClient',
        'from app.main import app',
        '',
        'client = TestClient(app)',
        '',
        'def test_health():',
        '    r = client.get("/health")',
        '    assert r.status_code == 200',
        '    assert r.json() == {"status": "ok"}',
        '',
      ].join('\n'),
    });
  }
  if (c.docker) {
    files.push({
      path: 'Dockerfile',
      content: [
        'FROM python:3.12-slim',
        'WORKDIR /app',
        'COPY requirements.txt .',
        'RUN pip install --no-cache-dir -r requirements.txt',
        'COPY . .',
        'EXPOSE 8000',
        'CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]',
        '',
      ].join('\n'),
    });
  }
  if (c.ci) {
    files.push({
      path: '.github/workflows/ci.yml',
      content: [
        'name: CI',
        'on: [push, pull_request]',
        'jobs:',
        '  test:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/setup-python@v5',
        '        with: { python-version: "3.12" }',
        '      - run: pip install -r requirements.txt',
        '      - run: pytest',
        '',
      ].join('\n'),
    });
  }
  files.push({
    path: 'README.md',
    content: `# ${c.name}\n\n${c.description}\n\n## Getting started\n\n\`\`\`bash\npython -m venv .venv && source .venv/bin/activate\npip install -r requirements.txt\ncp .env.example .env\nuvicorn app.main:app --reload\n\`\`\`\n`,
  });
  return files;
}

/** Build the `cli-tool` (Commander.js) template. */
function buildCliTool(c: TemplateBuildCtx): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: c.name,
      version: '0.1.0',
      type: 'module',
      bin: { [c.name]: './dist/main.js' },
      scripts: {
        dev: 'tsx src/main.ts',
        build: 'tsup',
        start: 'node dist/main.js',
        test: c.tests ? 'vitest run' : undefined,
      },
      dependencies: {
        commander: '^13.0.0',
        chalk: '^5.4.0',
      },
      devDependencies: {
        typescript: '^5.6.0',
        '@types/node': '^22.0.0',
        tsup: '^8.4.0',
        tsx: '^4.19.0',
        ...(c.tests ? { vitest: '^2.1.0' } : {}),
      },
    }, null, 2),
  });
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist', 'test'],
    }, null, 2),
  });
  files.push({
    path: 'tsup.config.ts',
    content: [
      "import { defineConfig } from 'tsup';",
      '',
      'export default defineConfig({',
      "  entry: ['src/main.ts'],",
      '  format: ["esm"],',
      '  dts: true,',
      '  clean: true,',
      '  sourcemap: true,',
      '});',
      '',
    ].join('\n'),
  });
  files.push({
    path: '.gitignore',
    content: ['node_modules/', 'dist/', '*.log'].join('\n') + '\n',
  });
  files.push({
    path: 'src/main.ts',
    content: [
      '#!/usr/bin/env node',
      "import { Command } from 'commander';",
      "import chalk from 'chalk';",
      '',
      'const program = new Command();',
      '',
      `program.name('${c.name}').description('${c.description}').version('0.1.0');`,
      '',
      "program.command('hello [name]').action((name?: string) => {",
      '  console.log(chalk.green(`Hello, ${name ?? "world"}!`));',
      '});',
      '',
      'program.parse();',
      '',
    ].join('\n'),
  });
  if (c.tests) {
    files.push({
      path: 'test/hello.test.ts',
      content: [
        "import { describe, it, expect } from 'vitest';",
        '',
        'describe("hello", () => {',
        '  it("passes", () => { expect(true).toBe(true); });',
        '});',
        '',
      ].join('\n'),
    });
  }
  if (c.docker) {
    files.push({
      path: 'Dockerfile',
      content: [
        'FROM node:20-alpine',
        'WORKDIR /app',
        'COPY package*.json ./',
        'RUN npm ci --omit=dev',
        'COPY dist ./dist',
        'ENTRYPOINT ["node", "dist/main.js"]',
        '',
      ].join('\n'),
    });
  }
  if (c.ci) {
    files.push({
      path: '.github/workflows/ci.yml',
      content: [
        'name: CI',
        'on: [push, pull_request]',
        'jobs:',
        '  test:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/setup-node@v4',
        '        with: { node-version: "20" }',
        '      - run: npm ci',
        '      - run: npm run build',
        '      - run: npm test',
        '',
      ].join('\n'),
    });
  }
  files.push({
    path: 'README.md',
    content: `# ${c.name}\n\n${c.description}\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm run build\n./dist/main.js hello world\n\`\`\`\n`,
  });
  return files;
}

/** Build the `library` (TypeScript library) template. */
function buildLibrary(c: TemplateBuildCtx): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: c.name,
      version: '0.1.0',
      type: 'module',
      main: './dist/index.js',
      module: './dist/index.js',
      types: './dist/index.d.ts',
      exports: {
        '.': {
          types: './dist/index.d.ts',
          import: './dist/index.js',
        },
      },
      files: ['dist', 'README.md'],
      scripts: {
        build: 'tsup',
        dev: 'tsup --watch',
        typecheck: 'tsc --noEmit',
        test: c.tests ? 'vitest run' : undefined,
      },
      devDependencies: {
        typescript: '^5.6.0',
        '@types/node': '^22.0.0',
        tsup: '^8.4.0',
        ...(c.tests ? { vitest: '^2.1.0' } : {}),
      },
    }, null, 2),
  });
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true,
      },
      include: ['src/**/*'],
      exclude: ['node_modules', 'dist', 'test'],
    }, null, 2),
  });
  files.push({
    path: 'tsup.config.ts',
    content: [
      "import { defineConfig } from 'tsup';",
      '',
      'export default defineConfig({',
      "  entry: ['src/index.ts'],",
      '  format: ["esm"],',
      '  dts: true,',
      '  clean: true,',
      '  sourcemap: true,',
      '});',
      '',
    ].join('\n'),
  });
  files.push({
    path: '.gitignore',
    content: ['node_modules/', 'dist/', '*.log', 'coverage/'].join('\n') + '\n',
  });
  files.push({
    path: 'src/index.ts',
    content: [
      '/**',
      ` * ${c.name} — ${c.description}`,
      ' */',
      '',
      '/** Add two numbers. */',
      'export function add(a: number, b: number): number {',
      '  return a + b;',
      '}',
      '',
    ].join('\n'),
  });
  if (c.tests) {
    files.push({
      path: 'test/index.test.ts',
      content: [
        "import { describe, it, expect } from 'vitest';",
        "import { add } from '../src/index';",
        '',
        'describe("add", () => {',
        '  it("adds", () => { expect(add(1, 2)).toBe(3); });',
        '});',
        '',
      ].join('\n'),
    });
  }
  if (c.docker) {
    // Libraries usually don't need Docker, but include a minimal one.
    files.push({
      path: 'Dockerfile',
      content: [
        'FROM node:20-alpine',
        'WORKDIR /app',
        'COPY package*.json ./',
        'RUN npm ci',
        'COPY . .',
        'RUN npm run build',
        '',
      ].join('\n'),
    });
  }
  if (c.ci) {
    files.push({
      path: '.github/workflows/ci.yml',
      content: [
        'name: CI',
        'on: [push, pull_request]',
        'jobs:',
        '  test:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - uses: actions/checkout@v4',
        '      - uses: actions/setup-node@v4',
        '        with: { node-version: "20" }',
        '      - run: npm ci',
        '      - run: npm run build',
        '      - run: npm test',
        '',
      ].join('\n'),
    });
  }
  files.push({
    path: 'README.md',
    content: `# ${c.name}\n\n${c.description}\n\n## Install\n\n\`\`\`bash\nnpm install ${c.name}\n\`\`\`\n\n## Usage\n\n\`\`\`ts\nimport { add } from '${c.name}';\n\nconsole.log(add(1, 2)); // 3\n\`\`\`\n`,
  });
  return files;
}
