/**
 * @file templates/bash.ts
 * @description Bash completion script generator (programmable completion).
 *
 * Emits a `_sanix()` function + `complete -F _sanix sanix` binding.
 * Subcommands become case-arms; flags are listed for `-`/`--` prefix
 * matching; flag values use `COMPREPLY` with static enums or file
 * completion.
 */

import type { CompletionSpec, CompletionCommand, CompletionFlag } from '../CompletionGenerator.js';
import type { RenderOptions } from './index.js';

/**
 * Render a bash completion script.
 * @param spec Completion spec.
 * @param opts Render options.
 */
export function renderBash(spec: CompletionSpec, opts: RenderOptions = {}): string {
  const ind = opts.indent ?? '  ';
  const L: string[] = [];
  L.push(`# Bash completion for ${spec.name}`);
  L.push(`# Generated by @sanix/completions. Do not edit by hand.`);
  L.push(`# Install: source this file from your ~/.bashrc, or drop it in ~/.bash_completion.d/`);
  L.push('');
  L.push(`_${spec.name}() {`);
  L.push(`${ind}local cur prev words cword`);
  L.push(`${ind}_init_completion || return`);
  L.push('');
  L.push(`${ind}local cmd="${spec.name}"`);
  L.push(`${ind}local i=1`);
  L.push(`${ind}while [[ $i -lt $cword ]]; do`);
  L.push(`${ind}${ind}case "\${words[i]}" in`);
  L.push(`${ind}${ind}  -*) ;;`);
  L.push(`${ind}${ind}  *) cmd="\${words[i]}"; break ;;`);
  L.push(`${ind}${ind}esac`);
  L.push(`${ind}${ind}i=$((i+1))`);
  L.push(`${ind}done`);
  L.push('');
  const globalFlags = spec.globalFlags ?? [];
  L.push(`${ind}local global_opts="${flagList(globalFlags)}"`);
  L.push('');
  if (spec.subcommands && spec.subcommands.length > 0) {
    L.push(`${ind}case "$cmd" in`);
    L.push(`${ind}${ind}${spec.name})`);
    L.push(`${ind}${ind}${ind}if [[ "$cur" == -* ]]; then`);
    L.push(`${ind}${ind}${ind}${ind}COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )`);
    L.push(`${ind}${ind}${ind}else`);
    L.push(`${ind}${ind}${ind}${ind}local subs="${spec.subcommands.map((s) => s.name).join(' ')}"`);
    L.push(`${ind}${ind}${ind}${ind}COMPREPLY=( $(compgen -W "$subs" -- "$cur") )`);
    L.push(`${ind}${ind}${ind}fi`);
    L.push(`${ind}${ind}${ind};;`);
    for (const sub of spec.subcommands) {
      renderBashCommand(sub, ind, L);
    }
    L.push(`${ind}esac`);
  } else {
    L.push(`${ind}if [[ "$cur" == -* ]]; then`);
    L.push(`${ind}${ind}COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )`);
    L.push(`${ind}fi`);
  }
  L.push('');
  L.push(`${ind}return 0`);
  L.push(`}`);
  L.push('');
  L.push(`complete -F _${spec.name} ${spec.name}`);
  return L.join('\n');
}

/** Render a single subcommand's case-arm. */
function renderBashCommand(cmd: CompletionCommand, ind: string, L: string[]): void {
  const allNames = [cmd.name, ...(cmd.aliases ?? [])].join('|');
  L.push(`${ind}${ind}${allNames})`);
  const flags = flagList(cmd.flags ?? []);
  L.push(`${ind}${ind}${ind}local opts="${flags}"`);
  L.push(`${ind}${ind}${ind}case "$cur" in`);
  L.push(`${ind}${ind}${ind}  -*) COMPREPLY=( $(compgen -W "$opts" -- "$cur") ) ;;`);
  L.push(`${ind}${ind}${ind}  *)`);
  L.push(`${ind}${ind}${ind}${ind}case "$prev" in`);
  for (const f of cmd.flags ?? []) {
    if (f.takesValue && f.values?.static) {
      const names = [f.long, f.short].filter(Boolean).join('|');
      L.push(`${ind}${ind}${ind}${ind}${ind}${names}) COMPREPLY=( $(compgen -W "${f.values.static.join(' ')}" -- "$cur") ) ;;`);
    }
  }
  L.push(`${ind}${ind}${ind}${ind}${ind}*)`);
  const fileArg = (cmd.args ?? []).find((a) => a.values?.hint === 'file');
  if (fileArg) {
    L.push(`${ind}${ind}${ind}${ind}${ind}${ind}COMPREPLY=( $(compgen -f -- "$cur") ) ;;`);
  } else {
    L.push(`${ind}${ind}${ind}${ind}${ind}${ind}COMPREPLY=() ;;`);
  }
  L.push(`${ind}${ind}${ind}${ind}esac`);
  L.push(`${ind}${ind}${ind}  ;;`);
  L.push(`${ind}${ind}${ind}esac`);
  if (cmd.subcommands && cmd.subcommands.length > 0) {
    L.push(`${ind}${ind}${ind}local subs="${cmd.subcommands.map((s) => s.name).join(' ')}"`);
    L.push(`${ind}${ind}${ind}if [[ "$cur" != -* ]]; then`);
    L.push(`${ind}${ind}${ind}${ind}COMPREPLY=( $(compgen -W "$subs" -- "$cur") )`);
    L.push(`${ind}${ind}${ind}fi`);
  }
  L.push(`${ind}${ind}${ind};;`);
}

/** Build a space-separated flag list string. */
function flagList(flags: CompletionFlag[]): string {
  const names: string[] = [];
  for (const f of flags) {
    if (f.long) names.push(f.long);
    if (f.short) names.push(f.short);
    for (const a of f.aliases ?? []) names.push(a);
  }
  return names.join(' ');
}
