/**
 * @file templates/elvish.ts
 * @description Elvish completion script generator.
 *
 * Emits an `edit:completion:arg-completer[sanix] = [@args]{ ... }`
 * closure that returns `edit:complex-candidate` entries. Elvish's
 * completion model is closure-based — the closure receives the full
 * command line as `@args` and emits candidates for the last token.
 */

import type { CompletionSpec, CompletionCommand } from '../CompletionGenerator.js';
import type { RenderOptions } from './index.js';

/**
 * Render an elvish completion script.
 */
export function renderElvish(spec: CompletionSpec, opts: RenderOptions = {}): string {
  const ind = opts.indent ?? '  ';
  const L: string[] = [];
  L.push(`# Elvish completion for ${spec.name}`);
  L.push(`# Generated by @sanix/completions. Do not edit by hand.`);
  L.push(`# Install: use this file from your rc.elv, or drop in ~/.config/elvish/lib/`);
  L.push('');
  L.push(`edit:completion:arg-completer[${spec.name}] = [@args]{`);
  L.push(`${ind}if (== (count $args) 0) {`);
  L.push(`${ind}${ind}return`);
  L.push(`${ind}}`);
  L.push('');
  L.push(`${ind}cur = $args[(- 1)]`);
  L.push(`${ind}prev = $args[(- 2)]`);
  L.push('');
  // Global flags
  const globalFlags = spec.globalFlags ?? [];
  if (globalFlags.length > 0) {
    L.push(`${ind}global-flags = [`);
    for (const f of globalFlags) {
      const names = [f.long, f.short].filter(Boolean);
      for (const n of names) {
        L.push(`${ind}${ind}edit:complex-candidate ${n} &display='${escapeElvish(f.description)}'`);
      }
    }
    L.push(`${ind}]`);
  }
  // Subcommands
  if (spec.subcommands && spec.subcommands.length > 0) {
    L.push(`${ind}subs = [`);
    for (const sub of spec.subcommands) {
      if (sub.hidden) continue;
      L.push(`${ind}${ind}edit:complex-candidate ${sub.name} &display='${escapeElvish(sub.description)}'`);
      for (const a of sub.aliases ?? []) {
        L.push(`${ind}${ind}edit:complex-candidate ${a} &display='alias for ${sub.name}'`);
      }
    }
    L.push(`${ind}]`);
    L.push('');
    L.push(`${ind}if (== (count $args) 1) {`);
    L.push(`${ind}${ind}if (has-prefix $cur -) {`);
    L.push(`${ind}${ind}${ind}put $@global-flags`);
    L.push(`${ind}${ind}} else {`);
    L.push(`${ind}${ind}${ind}put $@subs`);
    L.push(`${ind}${ind}}`);
    L.push(`${ind}${ind}return`);
    L.push(`${ind}}`);
    L.push('');
    L.push(`${ind}cmd = $args[1]`);
    for (const sub of spec.subcommands) {
      renderElvishCommand(sub, ind, L);
    }
  } else {
    L.push(`${ind}if (has-prefix $cur -) {`);
    L.push(`${ind}${ind}put $@global-flags`);
    L.push(`${ind}}`);
  }
  L.push(`}`);
  return L.join('\n');
}

/** Render a single subcommand's completion branch. */
function renderElvishCommand(cmd: CompletionCommand, ind: string, L: string[]): void {
  const names = [cmd.name, ...(cmd.aliases ?? [])];
  L.push(`${ind}if (or ${names.map((n) => `(== $cmd ${n})`).join(' ')}) {`);
  const flags = cmd.flags ?? [];
  if (flags.length > 0) {
    L.push(`${ind}${ind}opts = [`);
    for (const f of flags) {
      const fNames = [f.long, f.short].filter(Boolean);
      for (const n of fNames) {
        L.push(`${ind}${ind}${ind}edit:complex-candidate ${n} &display='${escapeElvish(f.description)}'`);
      }
    }
    L.push(`${ind}${ind}]`);
  }
  L.push(`${ind}${ind}if (has-prefix $cur -) {`);
  if (flags.length > 0) {
    L.push(`${ind}${ind}${ind}put $@opts`);
  }
  L.push(`${ind}${ind}} else {`);
  // Flag-value completion: check prev against each value-bearing flag.
  for (const f of flags) {
    if (f.takesValue && f.values?.static) {
      const fNames = [f.long, f.short].filter(Boolean);
      const cond = fNames.map((n) => `(== $prev ${n})`).join(' ');
      L.push(`${ind}${ind}${ind}if (or ${cond}) {`);
      L.push(`${ind}${ind}${ind}${ind}put ${f.values.static.map((v) => `'${escapeElvish(v)}'`).join(' ')}`);
      L.push(`${ind}${ind}${ind}}`);
    }
  }
  L.push(`${ind}${ind}}`);
  L.push(`${ind}}`);
}

/** Escape single quotes for elvish strings. */
function escapeElvish(s: string): string {
  return s.replace(/'/g, "''");
}
