/**
 * @file templates/fish.ts
 * @description Fish shell completion script generator.
 *
 * Emits `complete -c sanix -n '__fish_use_subcommand' -a 'build' -d '...'`
 * lines — one per subcommand + one per flag + value-completion pairs.
 * Fish auto-loads `*.fish` files from `~/.config/fish/completions/`.
 */

import type { CompletionSpec, CompletionCommand, CompletionFlag } from '../CompletionGenerator.js';
import type { RenderOptions } from './index.js';

/**
 * Render a fish completion script.
 */
export function renderFish(spec: CompletionSpec, opts: RenderOptions = {}): string {
  const ind = opts.indent ?? '  ';
  const L: string[] = [];
  L.push(`# Fish completion for ${spec.name}`);
  L.push(`# Generated by @sanix/completions. Do not edit by hand.`);
  L.push(`# Install: drop in ~/.config/fish/completions/${spec.name}.fish`);
  L.push('');
  // Global flags (apply at every level).
  for (const f of spec.globalFlags ?? []) {
    renderFishFlag(spec.name, f, 'global', L, ind);
  }
  // Subcommands.
  if (spec.subcommands && spec.subcommands.length > 0) {
    for (const sub of spec.subcommands) {
      if (sub.hidden) continue;
      // Subcommand suggestion.
      L.push(`complete -c ${spec.name} -n '__fish_use_subcommand' -a '${sub.name}' -d '${escapeFish(sub.description)}'`);
      for (const a of sub.aliases ?? []) {
        L.push(`complete -c ${spec.name} -n '__fish_use_subcommand' -a '${a}' -d 'alias for ${sub.name}'`);
      }
      // Subcommand flags — condition on the subcommand being present.
      for (const f of sub.flags ?? []) {
        renderFishFlag(spec.name, f, sub.name, L, ind);
      }
      // Positional arg completion.
      for (const arg of sub.args ?? []) {
        renderFishArg(spec.name, arg, sub.name, L);
      }
      // Nested subcommands.
      for (const nested of sub.subcommands ?? []) {
        if (nested.hidden) continue;
        L.push(`complete -c ${spec.name} -n '__fish_seen_subcommand_from ${sub.name}' -a '${nested.name}' -d '${escapeFish(nested.description)}'`);
      }
    }
  }
  return L.join('\n');
}

/** Render a fish `complete` line for a flag. */
function renderFishFlag(rootName: string, f: CompletionFlag, scope: string, L: string[], _ind: string): void {
  const cond = scope === 'global'
    ? ''
    : ` -n '__fish_seen_subcommand_from ${scope}'`;
  const shortPart = f.short ? ` -s ${f.short.replace('-', '')}` : '';
  const longPart = f.long ? ` -l ${f.long.replace('--', '')}` : '';
  for (const a of f.aliases ?? []) {
    L.push(`complete -c ${rootName}${cond} -l ${a.replace('--', '')} -d '${escapeFish(f.description)}'`);
  }
  const reqArg = f.takesValue ? ' -r' : '';
  L.push(`complete -c ${rootName}${cond}${shortPart}${longPart}${reqArg} -d '${escapeFish(f.description)}'`);
  // Value completion.
  if (f.takesValue && f.values?.static) {
    const names = [f.long, f.short].filter(Boolean).map((n) => n.replace(/^-+/, ''));
    for (const n of names) {
      L.push(`complete -c ${rootName}${cond} -n '__fish_seen_subcommand_from ${scope}; and __fish_use_subcommand; and string match -q -- ${n}=\\* (commandline -ct)' -f -a '${f.values!.static!.join(' ')}'`);
    }
  } else if (f.takesValue && f.values?.hint === 'file') {
    const names = [f.long, f.short].filter(Boolean).map((n) => n.replace(/^-+/, ''));
    for (const n of names) {
      L.push(`complete -c ${rootName}${cond} -n '__fish_seen_subcommand_from ${scope}; and string match -q -- ${n}=\\* (commandline -ct)' -r -F`);
    }
  }
}

/** Render a fish `complete` line for a positional arg. */
function renderFishArg(rootName: string, arg: import('../CompletionGenerator.js').CompletionArg, scope: string, L: string[]): void {
  if (arg.values?.static) {
    L.push(`complete -c ${rootName} -n '__fish_seen_subcommand_from ${scope}' -f -a '${arg.values.static.join(' ')}' -d '${escapeFish(arg.description)}'`);
  } else if (arg.values?.hint === 'file') {
    L.push(`complete -c ${rootName} -n '__fish_seen_subcommand_from ${scope}' -r -F -d '${escapeFish(arg.description)}'`);
  }
}

/** Escape single quotes for fish descriptions. */
function escapeFish(s: string): string {
  return s.replace(/'/g, "\\'");
}
