/**
 * @file templates/powershell.ts
 * @description PowerShell completion script generator.
 *
 * Emits a `Register-ArgumentCompleter` script that wires a
 * `System.Management.Automation.CompletionResult`-returning handler
 * to the CLI binary. Subcommands are completed on the first token;
 * flags on `-`/`--` prefix; static enums via a parameter map.
 */

import type { CompletionSpec, CompletionCommand, CompletionFlag } from '../CompletionGenerator.js';
import type { RenderOptions } from './index.js';

/**
 * Render a PowerShell completion script.
 */
export function renderPowerShell(spec: CompletionSpec, opts: RenderOptions = {}): string {
  const ind = opts.indent ?? '  ';
  const L: string[] = [];
  L.push(`# PowerShell completion for ${spec.name}`);
  L.push(`# Generated by @sanix/completions. Do not edit by hand.`);
  L.push(`# Install: Import-Module this file from your $PROFILE.`);
  L.push('');
  L.push(`using namespace System.Management.Automation`);
  L.push(`using namespace System.Management.Automation.Language`);
  L.push('');
  L.push(`$${spec.name}Completer = {`);
  L.push(`${ind}param($wordToComplete, $commandAst, $cursorPosition)`);
  L.push('');
  L.push(`${ind}$tokens = $commandAst.CommandElements | ForEach-Object { $_.Value }`);
  L.push(`${ind}$current = $wordToComplete`);
  L.push(`${ind}$prev = if ($tokens.Count -ge 2) { $tokens[$tokens.Count - 2] } else { '' }`);
  L.push('');
  // Build the subcommand map.
  if (spec.subcommands && spec.subcommands.length > 0) {
    L.push(`${ind}$subcommands = @{`);
    for (const sub of spec.subcommands) {
      if (sub.hidden) continue;
      L.push(`${ind}${ind}'${sub.name}' = '${escapePS(sub.description)}'`);
      for (const a of sub.aliases ?? []) L.push(`${ind}${ind}'${a}' = 'alias for ${sub.name}'`);
    }
    L.push(`${ind}}`);
  }
  // Global flags
  L.push(`${ind}$globalFlags = @(${(spec.globalFlags ?? []).flatMap((f) => [f.long, f.short].filter(Boolean)).map((n) => `'${n}'`).join(', ')})`);
  L.push('');
  L.push(`${ind}$results = @()`);
  L.push('');
  L.push(`${ind}if ($current.StartsWith('-')) {`);
  L.push(`${ind}${ind}foreach ($f in $globalFlags) {`);
  L.push(`${ind}${ind}${ind}if ($f.StartsWith($current)) {`);
  L.push(`${ind}${ind}${ind}${ind}$results += [CompletionResult]::new($f, $f, 'ParameterValue', $f)`);
  L.push(`${ind}${ind}${ind}}`);
  L.push(`${ind}${ind}}`);
  L.push(`${ind}} elseif ($subcommands) {`);
  L.push(`${ind}${ind}foreach ($name in $subcommands.Keys) {`);
  L.push(`${ind}${ind}${ind}if ($name.StartsWith($current)) {`);
  L.push(`${ind}${ind}${ind}${ind}$results += [CompletionResult]::new($name, $name, 'ParameterValue', $subcommands[$name])`);
  L.push(`${ind}${ind}${ind}}`);
  L.push(`${ind}${ind}}`);
  L.push(`${ind}}`);
  L.push('');
  // Flag value completion per subcommand.
  if (spec.subcommands && spec.subcommands.length > 0) {
    L.push(`${ind}switch -Regex ($prev) {`);
    for (const sub of spec.subcommands) {
      for (const f of sub.flags ?? []) {
        if (f.takesValue && f.values?.static) {
          const pattern = [f.long, f.short].filter(Boolean).map((n) => `^${escapeRegex(n)}$`).join('|');
          L.push(`${ind}${ind}'${pattern}' {`);
          L.push(`${ind}${ind}${ind}foreach ($v in @(${f.values.static.map((v) => `'${escapePS(v)}'`).join(', ')})) {`);
          L.push(`${ind}${ind}${ind}${ind}if ($v.StartsWith($current)) { $results += [CompletionResult]::new($v, $v, 'ParameterValue', $v) }`);
          L.push(`${ind}${ind}${ind}}`);
          L.push(`${ind}${ind}}`);
        }
      }
    }
    L.push(`${ind}}`);
  }
  L.push('');
  L.push(`${ind}return $results`);
  L.push(`}`);
  L.push('');
  L.push(`Register-ArgumentCompleter -Native -CommandName '${spec.name}' -ScriptBlock $${spec.name}Completer`);
  return L.join('\n');
}

function escapePS(s: string): string {
  return s.replace(/'/g, "''");
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Re-exported for the InstallHelper (unused here, keeps the module self-contained). */
export function _renderPSCommand(_cmd: CompletionCommand, _ind: string, _L: string[]): void {
  /* placeholder for symmetry with bash/zsh renderers */
}

/** Re-exported flag-list helper (unused here). */
export function _psFlagList(_flags: CompletionFlag[]): string {
  return '';
}
