/**
 * @file templates/zsh.ts
 * @description Zsh completion script generator (`_sanix` function).
 *
 * Emits a zsh `#compdef`-style completion function using the
 * `_arguments` builtin. Subcommands become `':subcommand:->sub'`
 * states; flags become `'-*[flag]:description:'` entries; flag values
 * use `:value:(a b c)` for static enums or `:file:_files` for file
 * completion.
 */

import type { CompletionSpec, CompletionCommand, CompletionFlag, CompletionArg } from '../CompletionGenerator.js';
import type { RenderOptions } from './index.js';

/**
 * Render a zsh completion script.
 */
export function renderZsh(spec: CompletionSpec, opts: RenderOptions = {}): string {
  const ind = opts.indent ?? '  ';
  const L: string[] = [];
  L.push(`#compdef ${spec.name}`);
  L.push(`# Zsh completion for ${spec.name}`);
  L.push(`# Generated by @sanix/completions. Do not edit by hand.`);
  L.push(`# Install: drop in a directory on $fpath (e.g. ~/.zsh/completions/_${spec.name})`);
  L.push('');
  L.push(`_${spec.name}() {`);
  L.push(`${ind}local -a opts subs`);
  L.push(`${ind}local context state line curcontext="$curcontext"`);
  L.push('');
  // Global flags
  const globalFlagArgs = (spec.globalFlags ?? []).map((f) => zshFlagArg(f)).filter(Boolean);
  L.push(`${ind}opts=(`);
  for (const a of globalFlagArgs) L.push(`${ind}${ind}${a}`);
  L.push(`${ind})`);
  L.push('');
  // Subcommand list
  if (spec.subcommands && spec.subcommands.length > 0) {
    L.push(`${ind}subs=(`);
    for (const s of spec.subcommands) {
      if (s.hidden) continue;
      L.push(`${ind}${ind}'${s.name}[${escapeZsh(s.description)}]'`);
      for (const a of s.aliases ?? []) L.push(`${ind}${ind}'${a}[alias for ${s.name}]'`);
    }
    L.push(`${ind})`);
    L.push('');
    L.push(`${ind}_arguments -C \\`);
    L.push(`${ind}${ind}'1: :->subs' \\`);
    L.push(`${ind}${ind}'*::arg:->args'`);
    L.push('');
    L.push(`${ind}case $state in`);
    L.push(`${ind}${ind}subs)`);
    L.push(`${ind}${ind}${ind}_describe '${spec.name} command' subs`);
    L.push(`${ind}${ind};;`);
    L.push(`${ind}${ind}args)`);
    L.push(`${ind}${ind}${ind}case $line[1] in`);
    for (const sub of spec.subcommands) {
      renderZshCommand(sub, ind, L);
    }
    L.push(`${ind}${ind}${ind}esac`);
    L.push(`${ind}${ind};;`);
    L.push(`${ind}esac`);
  } else {
    L.push(`${ind}_arguments -C \\`);
    for (const a of globalFlagArgs) L.push(`${ind}${ind}'${a}' \\`);
    L.push(`${ind}${ind}'*: : '`);
  }
  L.push('');
  L.push(`${ind}return 0`);
  L.push(`}`);
  L.push('');
  L.push(`_${spec.name} "$@"`);
  return L.join('\n');
}

/** Render a single subcommand's args case-arm. */
function renderZshCommand(cmd: CompletionCommand, ind: string, L: string[]): void {
  const names = [cmd.name, ...(cmd.aliases ?? [])].join('|');
  L.push(`${ind}${ind}${ind}(${names})`);
  const flagArgs = (cmd.flags ?? []).map((f) => zshFlagArg(f)).filter(Boolean);
  const argArgs = (cmd.args ?? []).map((a) => zshPosArg(a));
  const all = [...flagArgs, ...argArgs];
  if (all.length > 0) {
    L.push(`${ind}${ind}${ind}${ind}_arguments -C \\`);
    for (let i = 0; i < all.length; i++) {
      L.push(`${ind}${ind}${ind}${ind}${ind}'${all[i]}'${i < all.length - 1 ? ' \\' : ''}`);
    }
  } else {
    L.push(`${ind}${ind}${ind}${ind}_arguments -C '*: :'`);
  }
  // Nested subcommands
  if (cmd.subcommands && cmd.subcommands.length > 0) {
    L.push(`${ind}${ind}${ind}${ind}local -a sub_subs`);
    L.push(`${ind}${ind}${ind}${ind}sub_subs=(`);
    for (const s of cmd.subcommands) {
      if (s.hidden) continue;
      L.push(`${ind}${ind}${ind}${ind}${ind}'${s.name}[${escapeZsh(s.description)}]'`);
    }
    L.push(`${ind}${ind}${ind}${ind})`);
    L.push(`${ind}${ind}${ind}${ind}_describe '${cmd.name} subcommand' sub_subs`);
  }
  L.push(`${ind}${ind}${ind};;`);
}

/** Build a zsh `_arguments` entry for a flag. */
function zshFlagArg(f: CompletionFlag): string | null {
  const parts: string[] = [];
  const descs: string[] = [];
  if (f.long) descs.push(`'${f.long}[${escapeZsh(f.description)}]'`);
  if (f.short) descs.push(`'${f.short}[${escapeZsh(f.description)}]'`);
  if (descs.length === 0) return null;
  if (f.takesValue) {
    const valuePart = f.values?.static
      ? `:${f.valueLabel ?? 'value'}:(${f.values.static.join(' ')})`
      : f.values?.hint === 'file'
        ? `:${f.valueLabel ?? 'file'}:_files`
        : `:${f.valueLabel ?? 'value'}:_default`;
    return `{${[f.long, f.short].filter(Boolean).join(',')}}${valuePart}`;
  }
  return `{${[f.long, f.short].filter(Boolean).join(',')}}`;
}

/** Build a zsh `_arguments` entry for a positional arg. */
function zshPosArg(a: CompletionArg): string {
  const valuePart = a.values?.static
    ? `:(${a.values.static.join(' ')})`
    : a.values?.hint === 'file'
      ? `:_files`
      : `:_default`;
  return `:${a.name}:${valuePart}`;
}

/** Escape `[`, `]`, `:` in zsh descriptions. */
function escapeZsh(s: string): string {
  return s.replace(/([\][':])/g, '\\$1');
}
